#!/usr/bin/env python3
"""Bundle the workspace source and shared theme into the portable HTML."""
from pathlib import Path
import json

root = Path(__file__).resolve().parent
workspace = root / 'workspace'
# JSON is the editable source. A classic script also supports file:// previews.
fixture = json.loads((workspace / 'fixtures/sapiens-cases.json').read_text())
# Escape '<' so guest </script> tags cannot close the portable shell's script.
fixture_json = json.dumps(fixture, ensure_ascii=False, separators=(',', ':')).replace('<', '\\u003c')
fixture_js = "// Generated by build-prototype.py; edit sapiens-cases.json instead.\n" + "globalThis.CorporaFixture = " + fixture_json + ";\n" + r'''(() => {
  const fixture = globalThis.CorporaFixture;
  const escape = value => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  for (const artifact of fixture.artifacts) {
    artifact.html = artifact.filename.endsWith('.html') ? artifact.content : artifact.previewHtml ||
      `<!doctype html><meta charset="utf-8"><meta name="color-scheme" content="light dark"><title>${escape(artifact.title)}</title><style>body{max-width:900px;margin:32px auto;padding:0 24px;font:15px/1.6 system-ui}pre{white-space:pre-wrap;overflow-wrap:anywhere}</style><h1>${escape(artifact.title)}</h1><pre>${escape(artifact.content)}</pre>`;
  }
  for (const workspace of Object.values(fixture.state.workspaces)) {
    for (const tab of workspace.tabs) {
      const artifact = fixture.artifacts.find(a => a.id === tab.artifactId);
      if (!artifact) throw new Error(`Missing fixture artifact: ${tab.artifactId}`);
      tab.html = artifact.html;
    }
  }
  const selected = fixture.state.workspaces[fixture.state.selected];
  fixture.state.tabs = selected.tabs;
  fixture.state.activeTab = selected.activeTab;
})();
'''
(workspace / 'fixtures/sapiens-cases.js').write_text(fixture_js)
html = (workspace / 'index.html').read_text()
html = html.replace('<script src="fixtures/sapiens-cases.js"></script>', '<script>\n' + fixture_js + '\n</script>')
for href, path in [('styles.css', workspace / 'styles.css'), ('../assets/sapi-theme.css', root / 'assets/sapi-theme.css')]:
    html = html.replace(f'<link rel="stylesheet" href="{href}">', '<style>\n' + path.read_text() + '\n</style>')
html = html.replace('<script src="../assets/sapi-theme.js"></script>', '<script>\n' + (root / 'assets/sapi-theme.js').read_text() + '\n</script>')
html = html.replace('<script src="../assets/group-avatar.js"></script>', '<script>\n' + (root / 'assets/group-avatar.js').read_text() + '\n</script>')
html = html.replace('<script src="app.js"></script>', '<script>\n' + (workspace / 'app.js').read_text() + '\n</script>')
(workspace / 'demo-corpora-ui.html').write_text(html)
print('Built workspace/demo-corpora-ui.html')
